default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", "5") %>
  min_messages: warning

development:
  <<: *default
  database: opensourcerails_development
  # connection timeout
  timeout: 5000
  variables:
    statement_timeout: "20s"

test:
  <<: *default
  database: opensourcerails_test

production:
  <<: *default
  database: opensourcerails_production
  username: rails
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  # connection timeout
  timeout: 5000
  variables:
    statement_timeout: "20s"
