development:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - [default, 20]
  - [ahoy, 10]
:schedule:
  Bulk::Projects::SyncProjectsWorker:
    every: '24h'
  Bulk::Projects::WeeklySyncProjectsWorker:
    every: '7d'
