# frozen_string_literal: true

if Rails.env.development?
  AdminUser.delete_all
  ActsAsTaggableOn::Tag.destroy_all
  Project.destroy_all
  AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

  ActsAsTaggableOn::Tag.create!([
                                  { name: "bunny", data: { "stack"=>true, "notable"=>true } },
                                  { name: "haml-rails", data: { "stack"=>true } },
                                  { name: "stripe", data: { "stack"=>true, "notable"=>false } },
                                  { name: "stimulus-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "importmap-rails", data: { "stack"=>true, "notable"=>false } },
                                  { name: "rspec-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "apartment", data: { "stack"=>true, "notable"=>true } },
                                  { name: "delayed_job_active_record", data: { "stack"=>true } },
                                  { name: "view_component", data: { "stack"=>true, "notable"=>true } },
                                  { name: "liquid", data: { "stack"=>true, "notable"=>false } },
                                  { name: "delayed_job", data: { "stack"=>true } },
                                  { name: "@hotwired/turbo-rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "mongoid", data: { "stack"=>true, "notable"=>true } },
                                  { name: "react_on_rails", data: { "stack"=>true, "notable"=>true } },
                                  { name: "handlebars", data: { "stack"=>true } },
                                  { name: "elasticsearch", data: { "stack"=>true, "notable"=>true } },
                                  { name: "mysql2", data: { "stack"=>true, "notable"=>false } },
                                  { name: "active_model_serializers", data: { "stack"=>true } },
                                  { name: "parallel_tests", data: { "stack"=>true, "notable"=>true } },
                                  { name: "postcss", data: { "stack"=>true, "notable"=>false } },
                                  { name: "preact", data: { "stack"=>true, "notable"=>true } },
                                  { name: "haml", data: { "stack"=>true, "notable"=>true } },
                                  { name: "stimulus", data: { "stack"=>true, "notable"=>true } },
                                  { name: "bootstrap", data: { "stack"=>true, "notable"=>true } },
                                  { name: "pg", data: { "stack"=>true, "notable"=>false } },
                                  { name: "turbolinks", data: { "stack"=>true, "notable"=>true } },
                                  { name: "elasticsearch-rails", data: { "stack"=>true } },
                                  { name: "elasticsearch-model", data: { "stack"=>true } },
                                  { name: "vue", data: { "stack"=>true, "notable"=>true } },
                                  { name: "backbone", data: { "stack"=>true, "notable"=>true } },
                                  { name: "react", data: { "stack"=>true, "notable"=>true } },
                                  { name: "webpack", data: { "stack"=>true } },
                                  { name: "activemerchant", data: { "stack"=>true } },
                                  { name: "gon", data: { "stack"=>true } },
                                  { name: "coffeescript", data: { "stack"=>true } },
                                  { name: "tailwindcss", data: { "stack"=>true, "notable"=>true } },
                                ])

  Project.create!({
                    name: "Discourse",
                    slug: "discourse",
                    rails_major_version: "5",
                    github: "discourse/discourse",
                    github_about: "A platform for community discussion. Free, open, simple.",
                    website: "http://www.discourse.org",
                    contributors: "1",
                    dependents: "",
                    stars: "33895",
                    watchers: "1",
                    forks: "7344",
                    branch: "main",
                    meta_last_updated_at: "2021-08-26 18:07:14 UTC",
                    description: "next-generation discussion platform",
                    short_blurb: "",
                    last_activity_at: "2021-08-26 17:38:34 UTC",
                    color: "#fbee6a",
                    last_commit: "334ec4edb6e370b880f86baa706ddcfd7fe1d7a2",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Forums", "Collaboration"],
                    license_list: ["Other"],
                    adjective_list: [],
                    gem_list: ["actionmailer", "actionpack", "actionview", "activemodel", "activerecord", "activesupport", "railties", "sprockets-rails", "json", "bootsnap", "sprockets", "actionview_precompiler", "seed-fu", "mail", "mini_mime", "mini_suffix", "redis", "redis-namespace", "active_model_serializers", "http_accept_language", "discourse-ember-rails", "discourse-ember-source", "ember-handlebars-template", "discourse-fonts", "barber", "message_bus", "rails_multisite", "fast_xs", "xorcist", "fastimage", "aws-sdk-s3", "aws-sdk-sns", "excon", "unf", "email_reply_trimmer", "image_optim", "multi_json", "mustache", "nokogiri", "loofah", "css_parser", "omniauth", "omniauth-facebook", "omniauth-twitter", "omniauth-github", "omniauth-oauth2", "omniauth-google-oauth2", "oj", "pg", "mini_sql", "pry-rails", "pry-byebug", "r2", "rake", "thor", "diffy", "rinku", "sidekiq", "mini_scheduler", "execjs", "mini_racer", "highline", "rack", "rack-protection", "cbor", "cose", "addressable", "json_schemer", "uglifier", "rtlit", "webmock", "fakeweb", "minitest", "simplecov", "test-prof", "rspec", "mock_redis", "listen", "certified", "fabrication", "mocha", "rb-fsevent", "rspec-rails", "shoulda-matchers", "rspec-html-matchers", "byebug", "rubocop-discourse", "parallel_tests", "rswag-specs", "annotate", "ruby-prof", "bullet", "better_errors", "binding_of_caller", "yaml-lint", "discourse_dev_assets", "faker", "fast_blank", "lru_redux", "htmlentities", "rack-mini-profiler", "unicorn", "puma", "rbtrace", "gc_tracer", "ruby-readability", "stackprof", "memory_profiler", "cppjieba_rb", "lograge", "logstash-event", "logstash-logger", "logster", "sassc", "sassc-rails", "rotp", "rqrcode", "rubyzip", "sshkey", "rchardet", "lz4-ruby", "sanitize", "webpush", "colored2", "maxminddb", "rails_failover"],
                    package_list: ["@fortawesome/fontawesome-free", "@highlightjs/cdn-assets", "@json-editor/json-editor", "@popperjs/core", "@uppy/aws-s3", "@uppy/aws-s3-multipart", "@uppy/core", "@uppy/drop-target", "@uppy/xhr-upload", "ace-builds", "blueimp-file-upload", "bootbox", "bootstrap", "chart.js", "chartjs-plugin-datalabels", "diffhtml", "eslint-config-discourse", "handlebars", "jquery", "jquery-color", "jquery-tags-input", "jquery.autoellipsis", "magnific-popup", "markdown-it", "moment", "moment-timezone", "moment-timezone-names-translations", "mousetrap", "pikaday", "resumablejs", "spectrum-colorpicker", "workbox-cacheable-response", "workbox-core", "workbox-expiration", "workbox-routing", "workbox-strategies", "workbox-sw"],
                    app_directory_list: ["assets", "controllers", "helpers", "jobs", "mailers", "models", "serializers", "services", "views"],
                    backend_stack_list: ["redis", "pg", "sidekiq"],
                    frontend_stack_list: ["bootstrap"],
                  })
  Project.create!({
                    name: "Mastodon",
                    slug: "mastodon",
                    rails_major_version: "5",
                    github: "mastodon/mastodon",
                    github_about: "Your self-hosted, globally interconnected microblogging community",
                    website: "",
                    contributors: "1",
                    dependents: "",
                    stars: "24649",
                    watchers: "1",
                    forks: "4101",
                    branch: "main",
                    meta_last_updated_at: "2021-08-26 18:05:53 UTC",
                    description: "distributed, interconnected microblogging",
                    short_blurb: "Some really advanced concepts in this codebase if you're interested in distributed systems.",
                    last_activity_at: "2021-08-26 14:51:22 UTC",
                    color: "#686a6c",
                    last_commit: "60af89149d26d049e25dfe829ae54376a873c2b7",
                    hidden_at: "",
                    data: {},
                    pulse: "",
                    category_list: ["Social"],
                    license_list: ["GNU Affero General Public License v3.0"],
                    adjective_list: ["in-production"],
                    gem_list: ["pkg-config", "puma", "rails", "sprockets", "thor", "rack", "hamlit-rails", "pg", "makara", "pghero", "dotenv-rails", "aws-sdk-s3", "fog-core", "fog-openstack", "paperclip", "blurhash", "active_model_serializers", "addressable", "bootsnap", "browser", "charlock_holmes", "iso-639", "chewy", "cld3", "devise", "devise-two-factor", "devise_pam_authenticatable2", "net-ldap", "omniauth-cas", "omniauth-saml", "omniauth", "omniauth-rails_csrf_protection", "color_diff", "discard", "doorkeeper", "ed25519", "fast_blank", "fastimage", "hiredis", "redis-namespace", "htmlentities", "http", "http_accept_language", "httplog", "idn-ruby", "kaminari", "link_header", "mime-types", "nokogiri", "nsa", "oj", "ox", "parslet", "parallel", "posix-spawn", "pundit", "premailer-rails", "rack-attack", "rack-cors", "rails-i18n", "rails-settings-cached", "redis", "mario-redis-lock", "rqrcode", "ruby-progressbar", "sanitize", "scenic", "sidekiq", "sidekiq-scheduler", "sidekiq-unique-jobs", "sidekiq-bulk", "simple-navigation", "simple_form", "sprockets-rails", "stoplight", "strong_migrations", "tty-prompt", "twitter-text", "tzinfo-data", "webpacker", "webpush", "webauthn", "json-ld", "json-ld-preloaded", "rdf-normalize", "fabrication", "fuubar", "i18n-tasks", "pry-byebug", "pry-rails", "rspec-rails", "private_address_check", "capybara", "climate_control", "faker", "microformats", "rails-controller-testing", "rspec-sidekiq", "simplecov", "webmock", "parallel_tests", "rspec_junit_formatter", "active_record_query_trace", "annotate", "better_errors", "binding_of_caller", "bullet", "letter_opener", "letter_opener_web", "memory_profiler", "rubocop", "rubocop-rails", "brakeman", "bundler-audit", "capistrano", "capistrano-rails", "capistrano-rbenv", "capistrano-yarn", "stackprof", "lograge", "concurrent-ruby", "connection_pool", "xorcist"],
                    package_list: ["@babel/core", "@babel/plugin-proposal-decorators", "@babel/plugin-transform-react-inline-elements", "@babel/plugin-transform-runtime", "@babel/preset-env", "@babel/preset-react", "@babel/runtime", "@gamestdio/websocket", "@github/webauthn-json", "@rails/ujs", "array-includes", "arrow-key-navigation", "autoprefixer", "axios", "babel-loader", "babel-plugin-lodash", "babel-plugin-preval", "babel-plugin-react-intl", "babel-plugin-transform-react-remove-prop-types", "babel-runtime", "blurhash", "classnames", "color-blend", "compression-webpack-plugin", "cross-env", "css-loader", "cssnano", "detect-passive-events", "dotenv", "emoji-mart", "es6-symbol", "escape-html", "exif-js", "express", "file-loader", "font-awesome", "glob", "history", "http-link-header", "immutable", "imports-loader", "intersection-observer", "intl", "intl-messageformat", "intl-relativeformat", "is-nan", "js-yaml", "lodash", "mark-loader", "marky", "mini-css-extract-plugin", "mkdirp", "npmlog", "object-assign", "object-fit-images", "object.values", "offline-plugin", "path-complete-extname", "pg", "postcss-loader", "postcss-object-fit-images", "promise.prototype.finally", "prop-types", "punycode", "react", "react-dom", "react-hotkeys", "react-immutable-proptypes", "react-immutable-pure-component", "react-intl", "react-masonry-infinite", "react-motion", "react-notification", "react-overlays", "react-redux", "react-redux-loading-bar", "react-router-dom", "react-router-scroll-4", "react-select", "react-sparklines", "react-swipeable-views", "react-textarea-autosize", "react-toggle", "redis", "redux", "redux-immutable", "redux-thunk", "regenerator-runtime", "rellax", "requestidlecallback", "reselect", "rimraf", "sass", "sass-loader", "stacktrace-js", "stringz", "substring-trie", "terser-webpack-plugin", "tesseract.js", "throng", "tiny-queue", "twitter-text", "uuid", "webpack", "webpack-assets-manifest", "webpack-bundle-analyzer", "webpack-cli", "webpack-merge", "wicg-inert", "ws"],
                    app_directory_list: ["chewy", "controllers", "helpers", "javascript", "lib", "mailers", "models", "policies", "presenters", "serializers", "services", "validators", "views", "workers"],
                    backend_stack_list: ["pg", "redis", "sidekiq", "webpacker"],
                    frontend_stack_list: ["react"],
                  })
end
